// You can add your native dependencies here
dependencies {
  implementation 'androidx.security:security-crypto:1.1.0-alpha06'
  implementation 'androidx.datastore:datastore-preferences:1.0.0'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
}

android {
  compileSdkVersion 35
  buildToolsVersion "35"
  // ndkVersion ""

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 35

    // Version Information
    versionCode 1
    versionName "1.0.0"
    
    generatedDensities = []
  }

  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}
